/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ICodeRouteImport } from './routes/i.$code'
import { Route as DownloadVariantRouteImport } from './routes/download.$variant'
import { Route as AuthenticatedUndangRouteImport } from './routes/_authenticated.undang'
import { Route as AuthenticatedTugasBaruRouteImport } from './routes/_authenticated.tugas-baru'
import { Route as AuthenticatedTugasRouteImport } from './routes/_authenticated.tugas'
import { Route as AuthenticatedSesiRouteImport } from './routes/_authenticated.sesi'
import { Route as AuthenticatedRequestRouteImport } from './routes/_authenticated.request'
import { Route as AuthenticatedProfilChatRouteImport } from './routes/_authenticated.profil-chat'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPengaturanScrollGuardRouteImport } from './routes/_authenticated.pengaturan-scroll-guard'
import { Route as AuthenticatedPengaturanPenyimpananRouteImport } from './routes/_authenticated.pengaturan-penyimpanan'
import { Route as AuthenticatedPengaturanKunciRouteImport } from './routes/_authenticated.pengaturan-kunci'
import { Route as AuthenticatedPengaturanIntegrasiSosialRouteImport } from './routes/_authenticated.pengaturan-integrasi-sosial'
import { Route as AuthenticatedPengaturanBahasaRouteImport } from './routes/_authenticated.pengaturan-bahasa'
import { Route as AuthenticatedPengaturanAppModeRouteImport } from './routes/_authenticated.pengaturan-app-mode'
import { Route as AuthenticatedPengaturanApkRouteImport } from './routes/_authenticated.pengaturan-apk'
import { Route as AuthenticatedPengaturanAksesibilitasRouteImport } from './routes/_authenticated.pengaturan-aksesibilitas'
import { Route as AuthenticatedNotifikasiRouteImport } from './routes/_authenticated.notifikasi'
import { Route as AuthenticatedLinkPegawaiRouteImport } from './routes/_authenticated.link-pegawai'
import { Route as AuthenticatedLabelPreviewRouteImport } from './routes/_authenticated.label-preview'
import { Route as AuthenticatedKontakRouteImport } from './routes/_authenticated.kontak'
import { Route as AuthenticatedHutangPiutangRouteImport } from './routes/_authenticated.hutang-piutang'
import { Route as AuthenticatedGudangRouteImport } from './routes/_authenticated.gudang'
import { Route as AuthenticatedEmailQueueRouteImport } from './routes/_authenticated.email-queue'
import { Route as AuthenticatedEcerRouteImport } from './routes/_authenticated.ecer'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated.diagnostics'
import { Route as AuthenticatedDeviceVerifyRouteImport } from './routes/_authenticated.device-verify'
import { Route as AuthenticatedChatAuditRouteImport } from './routes/_authenticated.chat-audit'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedCatatanRouteImport } from './routes/_authenticated.catatan'
import { Route as AuthenticatedBukuAlamatRouteImport } from './routes/_authenticated.buku-alamat'
import { Route as AuthenticatedBalasCepatRouteImport } from './routes/_authenticated.balas-cepat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated.chat.index'
import { Route as LovableVisualProdukListRouteImport } from './routes/lovable.visual.produk-list'
import { Route as LovableVisualKomponenReviewRouteImport } from './routes/lovable.visual.komponen-review'
import { Route as LovableVisualChatDeletedRouteImport } from './routes/lovable.visual.chat-deleted'
import { Route as ApiPublicPrepRealtimeTokenRouteImport } from './routes/api/public/prep-realtime-token'
import { Route as ApiPublicAiPingRouteImport } from './routes/api/public/ai-ping'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated.chat.$conversationId'
import { Route as AuthenticatedAdminWorkerPortalRouteImport } from './routes/_authenticated.admin.worker-portal'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksSecurityScanDailyRouteImport } from './routes/api/public/hooks/security-scan-daily'
import { Route as ApiPublicHooksEmailQueueMonitorRouteImport } from './routes/api/public/hooks/email-queue-monitor'
import { Route as AuthenticatedGudangPesananIdRouteImport } from './routes/_authenticated.gudang.pesanan.$id'
import { Route as AuthenticatedGudangPesananIdEditRouteImport } from './routes/_authenticated.gudang.pesanan.$id.edit'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ICodeRoute = ICodeRouteImport.update({
  id: '/i/$code',
  path: '/i/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadVariantRoute = DownloadVariantRouteImport.update({
  id: '/$variant',
  path: '/$variant',
  getParentRoute: () => DownloadRoute,
} as any)
const AuthenticatedUndangRoute = AuthenticatedUndangRouteImport.update({
  id: '/undang',
  path: '/undang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTugasBaruRoute = AuthenticatedTugasBaruRouteImport.update({
  id: '/tugas-baru',
  path: '/tugas-baru',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTugasRoute = AuthenticatedTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSesiRoute = AuthenticatedSesiRouteImport.update({
  id: '/sesi',
  path: '/sesi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestRoute = AuthenticatedRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilChatRoute = AuthenticatedProfilChatRouteImport.update({
  id: '/profil-chat',
  path: '/profil-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengaturanScrollGuardRoute =
  AuthenticatedPengaturanScrollGuardRouteImport.update({
    id: '/pengaturan-scroll-guard',
    path: '/pengaturan-scroll-guard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanPenyimpananRoute =
  AuthenticatedPengaturanPenyimpananRouteImport.update({
    id: '/pengaturan-penyimpanan',
    path: '/pengaturan-penyimpanan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanKunciRoute =
  AuthenticatedPengaturanKunciRouteImport.update({
    id: '/pengaturan-kunci',
    path: '/pengaturan-kunci',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanIntegrasiSosialRoute =
  AuthenticatedPengaturanIntegrasiSosialRouteImport.update({
    id: '/pengaturan-integrasi-sosial',
    path: '/pengaturan-integrasi-sosial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanBahasaRoute =
  AuthenticatedPengaturanBahasaRouteImport.update({
    id: '/pengaturan-bahasa',
    path: '/pengaturan-bahasa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanAppModeRoute =
  AuthenticatedPengaturanAppModeRouteImport.update({
    id: '/pengaturan-app-mode',
    path: '/pengaturan-app-mode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanApkRoute =
  AuthenticatedPengaturanApkRouteImport.update({
    id: '/pengaturan-apk',
    path: '/pengaturan-apk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanAksesibilitasRoute =
  AuthenticatedPengaturanAksesibilitasRouteImport.update({
    id: '/pengaturan-aksesibilitas',
    path: '/pengaturan-aksesibilitas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotifikasiRoute = AuthenticatedNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkPegawaiRoute =
  AuthenticatedLinkPegawaiRouteImport.update({
    id: '/link-pegawai',
    path: '/link-pegawai',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabelPreviewRoute =
  AuthenticatedLabelPreviewRouteImport.update({
    id: '/label-preview',
    path: '/label-preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontakRoute = AuthenticatedKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHutangPiutangRoute =
  AuthenticatedHutangPiutangRouteImport.update({
    id: '/hutang-piutang',
    path: '/hutang-piutang',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGudangRoute = AuthenticatedGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailQueueRoute = AuthenticatedEmailQueueRouteImport.update({
  id: '/email-queue',
  path: '/email-queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEcerRoute = AuthenticatedEcerRouteImport.update({
  id: '/ecer',
  path: '/ecer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeviceVerifyRoute =
  AuthenticatedDeviceVerifyRouteImport.update({
    id: '/device-verify',
    path: '/device-verify',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatAuditRoute = AuthenticatedChatAuditRouteImport.update({
  id: '/chat-audit',
  path: '/chat-audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatatanRoute = AuthenticatedCatatanRouteImport.update({
  id: '/catatan',
  path: '/catatan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBukuAlamatRoute = AuthenticatedBukuAlamatRouteImport.update({
  id: '/buku-alamat',
  path: '/buku-alamat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalasCepatRoute = AuthenticatedBalasCepatRouteImport.update({
  id: '/balas-cepat',
  path: '/balas-cepat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const LovableVisualProdukListRoute = LovableVisualProdukListRouteImport.update({
  id: '/lovable/visual/produk-list',
  path: '/lovable/visual/produk-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableVisualKomponenReviewRoute =
  LovableVisualKomponenReviewRouteImport.update({
    id: '/lovable/visual/komponen-review',
    path: '/lovable/visual/komponen-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableVisualChatDeletedRoute =
  LovableVisualChatDeletedRouteImport.update({
    id: '/lovable/visual/chat-deleted',
    path: '/lovable/visual/chat-deleted',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPrepRealtimeTokenRoute =
  ApiPublicPrepRealtimeTokenRouteImport.update({
    id: '/api/public/prep-realtime-token',
    path: '/api/public/prep-realtime-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiPingRoute = ApiPublicAiPingRouteImport.update({
  id: '/api/public/ai-ping',
  path: '/api/public/ai-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedAdminWorkerPortalRoute =
  AuthenticatedAdminWorkerPortalRouteImport.update({
    id: '/admin/worker-portal',
    path: '/admin/worker-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSecurityScanDailyRoute =
  ApiPublicHooksSecurityScanDailyRouteImport.update({
    id: '/api/public/hooks/security-scan-daily',
    path: '/api/public/hooks/security-scan-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailQueueMonitorRoute =
  ApiPublicHooksEmailQueueMonitorRouteImport.update({
    id: '/api/public/hooks/email-queue-monitor',
    path: '/api/public/hooks/email-queue-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGudangPesananIdRoute =
  AuthenticatedGudangPesananIdRouteImport.update({
    id: '/pesanan/$id',
    path: '/pesanan/$id',
    getParentRoute: () => AuthenticatedGudangRoute,
  } as any)
const AuthenticatedGudangPesananIdEditRoute =
  AuthenticatedGudangPesananIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedGudangPesananIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRouteWithChildren
  '/error': typeof ErrorRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/balas-cepat': typeof AuthenticatedBalasCepatRoute
  '/buku-alamat': typeof AuthenticatedBukuAlamatRoute
  '/catatan': typeof AuthenticatedCatatanRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/chat-audit': typeof AuthenticatedChatAuditRoute
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ecer': typeof AuthenticatedEcerRoute
  '/email-queue': typeof AuthenticatedEmailQueueRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/kontak': typeof AuthenticatedKontakRoute
  '/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pengaturan-aksesibilitas': typeof AuthenticatedPengaturanAksesibilitasRoute
  '/pengaturan-apk': typeof AuthenticatedPengaturanApkRoute
  '/pengaturan-app-mode': typeof AuthenticatedPengaturanAppModeRoute
  '/pengaturan-bahasa': typeof AuthenticatedPengaturanBahasaRoute
  '/pengaturan-integrasi-sosial': typeof AuthenticatedPengaturanIntegrasiSosialRoute
  '/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/pengaturan-penyimpanan': typeof AuthenticatedPengaturanPenyimpananRoute
  '/pengaturan-scroll-guard': typeof AuthenticatedPengaturanScrollGuardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/profil-chat': typeof AuthenticatedProfilChatRoute
  '/request': typeof AuthenticatedRequestRoute
  '/sesi': typeof AuthenticatedSesiRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/tugas-baru': typeof AuthenticatedTugasBaruRoute
  '/undang': typeof AuthenticatedUndangRoute
  '/download/$variant': typeof DownloadVariantRoute
  '/i/$code': typeof ICodeRoute
  '/t/$token': typeof TTokenRoute
  '/admin/worker-portal': typeof AuthenticatedAdminWorkerPortalRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/lovable/visual/chat-deleted': typeof LovableVisualChatDeletedRoute
  '/lovable/visual/komponen-review': typeof LovableVisualKomponenReviewRoute
  '/lovable/visual/produk-list': typeof LovableVisualProdukListRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRouteWithChildren
  '/error': typeof ErrorRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/balas-cepat': typeof AuthenticatedBalasCepatRoute
  '/buku-alamat': typeof AuthenticatedBukuAlamatRoute
  '/catatan': typeof AuthenticatedCatatanRoute
  '/chat-audit': typeof AuthenticatedChatAuditRoute
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ecer': typeof AuthenticatedEcerRoute
  '/email-queue': typeof AuthenticatedEmailQueueRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/kontak': typeof AuthenticatedKontakRoute
  '/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pengaturan-aksesibilitas': typeof AuthenticatedPengaturanAksesibilitasRoute
  '/pengaturan-apk': typeof AuthenticatedPengaturanApkRoute
  '/pengaturan-app-mode': typeof AuthenticatedPengaturanAppModeRoute
  '/pengaturan-bahasa': typeof AuthenticatedPengaturanBahasaRoute
  '/pengaturan-integrasi-sosial': typeof AuthenticatedPengaturanIntegrasiSosialRoute
  '/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/pengaturan-penyimpanan': typeof AuthenticatedPengaturanPenyimpananRoute
  '/pengaturan-scroll-guard': typeof AuthenticatedPengaturanScrollGuardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/profil-chat': typeof AuthenticatedProfilChatRoute
  '/request': typeof AuthenticatedRequestRoute
  '/sesi': typeof AuthenticatedSesiRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/tugas-baru': typeof AuthenticatedTugasBaruRoute
  '/undang': typeof AuthenticatedUndangRoute
  '/download/$variant': typeof DownloadVariantRoute
  '/i/$code': typeof ICodeRoute
  '/t/$token': typeof TTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/worker-portal': typeof AuthenticatedAdminWorkerPortalRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/lovable/visual/chat-deleted': typeof LovableVisualChatDeletedRoute
  '/lovable/visual/komponen-review': typeof LovableVisualKomponenReviewRoute
  '/lovable/visual/produk-list': typeof LovableVisualProdukListRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRouteWithChildren
  '/error': typeof ErrorRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/balas-cepat': typeof AuthenticatedBalasCepatRoute
  '/_authenticated/buku-alamat': typeof AuthenticatedBukuAlamatRoute
  '/_authenticated/catatan': typeof AuthenticatedCatatanRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/chat-audit': typeof AuthenticatedChatAuditRoute
  '/_authenticated/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/ecer': typeof AuthenticatedEcerRoute
  '/_authenticated/email-queue': typeof AuthenticatedEmailQueueRoute
  '/_authenticated/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/_authenticated/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/_authenticated/kontak': typeof AuthenticatedKontakRoute
  '/_authenticated/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/_authenticated/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/_authenticated/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/_authenticated/pengaturan-aksesibilitas': typeof AuthenticatedPengaturanAksesibilitasRoute
  '/_authenticated/pengaturan-apk': typeof AuthenticatedPengaturanApkRoute
  '/_authenticated/pengaturan-app-mode': typeof AuthenticatedPengaturanAppModeRoute
  '/_authenticated/pengaturan-bahasa': typeof AuthenticatedPengaturanBahasaRoute
  '/_authenticated/pengaturan-integrasi-sosial': typeof AuthenticatedPengaturanIntegrasiSosialRoute
  '/_authenticated/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/_authenticated/pengaturan-penyimpanan': typeof AuthenticatedPengaturanPenyimpananRoute
  '/_authenticated/pengaturan-scroll-guard': typeof AuthenticatedPengaturanScrollGuardRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/profil-chat': typeof AuthenticatedProfilChatRoute
  '/_authenticated/request': typeof AuthenticatedRequestRoute
  '/_authenticated/sesi': typeof AuthenticatedSesiRoute
  '/_authenticated/tugas': typeof AuthenticatedTugasRoute
  '/_authenticated/tugas-baru': typeof AuthenticatedTugasBaruRoute
  '/_authenticated/undang': typeof AuthenticatedUndangRoute
  '/download/$variant': typeof DownloadVariantRoute
  '/i/$code': typeof ICodeRoute
  '/t/$token': typeof TTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/worker-portal': typeof AuthenticatedAdminWorkerPortalRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/lovable/visual/chat-deleted': typeof LovableVisualChatDeletedRoute
  '/lovable/visual/komponen-review': typeof LovableVisualKomponenReviewRoute
  '/lovable/visual/produk-list': typeof LovableVisualProdukListRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/error'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/audit'
    | '/balas-cepat'
    | '/buku-alamat'
    | '/catatan'
    | '/chat'
    | '/chat-audit'
    | '/device-verify'
    | '/diagnostics'
    | '/ecer'
    | '/email-queue'
    | '/gudang'
    | '/hutang-piutang'
    | '/kontak'
    | '/label-preview'
    | '/link-pegawai'
    | '/notifikasi'
    | '/pengaturan-aksesibilitas'
    | '/pengaturan-apk'
    | '/pengaturan-app-mode'
    | '/pengaturan-bahasa'
    | '/pengaturan-integrasi-sosial'
    | '/pengaturan-kunci'
    | '/pengaturan-penyimpanan'
    | '/pengaturan-scroll-guard'
    | '/profil'
    | '/profil-chat'
    | '/request'
    | '/sesi'
    | '/tugas'
    | '/tugas-baru'
    | '/undang'
    | '/download/$variant'
    | '/i/$code'
    | '/t/$token'
    | '/admin/worker-portal'
    | '/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/lovable/visual/chat-deleted'
    | '/lovable/visual/komponen-review'
    | '/lovable/visual/produk-list'
    | '/chat/'
    | '/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/gudang/pesanan/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/download'
    | '/error'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/audit'
    | '/balas-cepat'
    | '/buku-alamat'
    | '/catatan'
    | '/chat-audit'
    | '/device-verify'
    | '/diagnostics'
    | '/ecer'
    | '/email-queue'
    | '/gudang'
    | '/hutang-piutang'
    | '/kontak'
    | '/label-preview'
    | '/link-pegawai'
    | '/notifikasi'
    | '/pengaturan-aksesibilitas'
    | '/pengaturan-apk'
    | '/pengaturan-app-mode'
    | '/pengaturan-bahasa'
    | '/pengaturan-integrasi-sosial'
    | '/pengaturan-kunci'
    | '/pengaturan-penyimpanan'
    | '/pengaturan-scroll-guard'
    | '/profil'
    | '/profil-chat'
    | '/request'
    | '/sesi'
    | '/tugas'
    | '/tugas-baru'
    | '/undang'
    | '/download/$variant'
    | '/i/$code'
    | '/t/$token'
    | '/'
    | '/admin/worker-portal'
    | '/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/lovable/visual/chat-deleted'
    | '/lovable/visual/komponen-review'
    | '/lovable/visual/produk-list'
    | '/chat'
    | '/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/gudang/pesanan/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/error'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/_authenticated/audit'
    | '/_authenticated/balas-cepat'
    | '/_authenticated/buku-alamat'
    | '/_authenticated/catatan'
    | '/_authenticated/chat'
    | '/_authenticated/chat-audit'
    | '/_authenticated/device-verify'
    | '/_authenticated/diagnostics'
    | '/_authenticated/ecer'
    | '/_authenticated/email-queue'
    | '/_authenticated/gudang'
    | '/_authenticated/hutang-piutang'
    | '/_authenticated/kontak'
    | '/_authenticated/label-preview'
    | '/_authenticated/link-pegawai'
    | '/_authenticated/notifikasi'
    | '/_authenticated/pengaturan-aksesibilitas'
    | '/_authenticated/pengaturan-apk'
    | '/_authenticated/pengaturan-app-mode'
    | '/_authenticated/pengaturan-bahasa'
    | '/_authenticated/pengaturan-integrasi-sosial'
    | '/_authenticated/pengaturan-kunci'
    | '/_authenticated/pengaturan-penyimpanan'
    | '/_authenticated/pengaturan-scroll-guard'
    | '/_authenticated/profil'
    | '/_authenticated/profil-chat'
    | '/_authenticated/request'
    | '/_authenticated/sesi'
    | '/_authenticated/tugas'
    | '/_authenticated/tugas-baru'
    | '/_authenticated/undang'
    | '/download/$variant'
    | '/i/$code'
    | '/t/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/worker-portal'
    | '/_authenticated/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/lovable/visual/chat-deleted'
    | '/lovable/visual/komponen-review'
    | '/lovable/visual/produk-list'
    | '/_authenticated/chat/'
    | '/_authenticated/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/_authenticated/gudang/pesanan/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ICodeRoute: typeof ICodeRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicAiPingRoute: typeof ApiPublicAiPingRoute
  ApiPublicPrepRealtimeTokenRoute: typeof ApiPublicPrepRealtimeTokenRoute
  LovableVisualChatDeletedRoute: typeof LovableVisualChatDeletedRoute
  LovableVisualKomponenReviewRoute: typeof LovableVisualKomponenReviewRoute
  LovableVisualProdukListRoute: typeof LovableVisualProdukListRoute
  ApiPublicHooksEmailQueueMonitorRoute: typeof ApiPublicHooksEmailQueueMonitorRoute
  ApiPublicHooksSecurityScanDailyRoute: typeof ApiPublicHooksSecurityScanDailyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$code': {
      id: '/i/$code'
      path: '/i/$code'
      fullPath: '/i/$code'
      preLoaderRoute: typeof ICodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$variant': {
      id: '/download/$variant'
      path: '/$variant'
      fullPath: '/download/$variant'
      preLoaderRoute: typeof DownloadVariantRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/_authenticated/undang': {
      id: '/_authenticated/undang'
      path: '/undang'
      fullPath: '/undang'
      preLoaderRoute: typeof AuthenticatedUndangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tugas-baru': {
      id: '/_authenticated/tugas-baru'
      path: '/tugas-baru'
      fullPath: '/tugas-baru'
      preLoaderRoute: typeof AuthenticatedTugasBaruRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tugas': {
      id: '/_authenticated/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof AuthenticatedTugasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sesi': {
      id: '/_authenticated/sesi'
      path: '/sesi'
      fullPath: '/sesi'
      preLoaderRoute: typeof AuthenticatedSesiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/request': {
      id: '/_authenticated/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AuthenticatedRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil-chat': {
      id: '/_authenticated/profil-chat'
      path: '/profil-chat'
      fullPath: '/profil-chat'
      preLoaderRoute: typeof AuthenticatedProfilChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-scroll-guard': {
      id: '/_authenticated/pengaturan-scroll-guard'
      path: '/pengaturan-scroll-guard'
      fullPath: '/pengaturan-scroll-guard'
      preLoaderRoute: typeof AuthenticatedPengaturanScrollGuardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-penyimpanan': {
      id: '/_authenticated/pengaturan-penyimpanan'
      path: '/pengaturan-penyimpanan'
      fullPath: '/pengaturan-penyimpanan'
      preLoaderRoute: typeof AuthenticatedPengaturanPenyimpananRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-kunci': {
      id: '/_authenticated/pengaturan-kunci'
      path: '/pengaturan-kunci'
      fullPath: '/pengaturan-kunci'
      preLoaderRoute: typeof AuthenticatedPengaturanKunciRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-integrasi-sosial': {
      id: '/_authenticated/pengaturan-integrasi-sosial'
      path: '/pengaturan-integrasi-sosial'
      fullPath: '/pengaturan-integrasi-sosial'
      preLoaderRoute: typeof AuthenticatedPengaturanIntegrasiSosialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-bahasa': {
      id: '/_authenticated/pengaturan-bahasa'
      path: '/pengaturan-bahasa'
      fullPath: '/pengaturan-bahasa'
      preLoaderRoute: typeof AuthenticatedPengaturanBahasaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-app-mode': {
      id: '/_authenticated/pengaturan-app-mode'
      path: '/pengaturan-app-mode'
      fullPath: '/pengaturan-app-mode'
      preLoaderRoute: typeof AuthenticatedPengaturanAppModeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-apk': {
      id: '/_authenticated/pengaturan-apk'
      path: '/pengaturan-apk'
      fullPath: '/pengaturan-apk'
      preLoaderRoute: typeof AuthenticatedPengaturanApkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-aksesibilitas': {
      id: '/_authenticated/pengaturan-aksesibilitas'
      path: '/pengaturan-aksesibilitas'
      fullPath: '/pengaturan-aksesibilitas'
      preLoaderRoute: typeof AuthenticatedPengaturanAksesibilitasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifikasi': {
      id: '/_authenticated/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AuthenticatedNotifikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/link-pegawai': {
      id: '/_authenticated/link-pegawai'
      path: '/link-pegawai'
      fullPath: '/link-pegawai'
      preLoaderRoute: typeof AuthenticatedLinkPegawaiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/label-preview': {
      id: '/_authenticated/label-preview'
      path: '/label-preview'
      fullPath: '/label-preview'
      preLoaderRoute: typeof AuthenticatedLabelPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontak': {
      id: '/_authenticated/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof AuthenticatedKontakRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hutang-piutang': {
      id: '/_authenticated/hutang-piutang'
      path: '/hutang-piutang'
      fullPath: '/hutang-piutang'
      preLoaderRoute: typeof AuthenticatedHutangPiutangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gudang': {
      id: '/_authenticated/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof AuthenticatedGudangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-queue': {
      id: '/_authenticated/email-queue'
      path: '/email-queue'
      fullPath: '/email-queue'
      preLoaderRoute: typeof AuthenticatedEmailQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ecer': {
      id: '/_authenticated/ecer'
      path: '/ecer'
      fullPath: '/ecer'
      preLoaderRoute: typeof AuthenticatedEcerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/device-verify': {
      id: '/_authenticated/device-verify'
      path: '/device-verify'
      fullPath: '/device-verify'
      preLoaderRoute: typeof AuthenticatedDeviceVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat-audit': {
      id: '/_authenticated/chat-audit'
      path: '/chat-audit'
      fullPath: '/chat-audit'
      preLoaderRoute: typeof AuthenticatedChatAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catatan': {
      id: '/_authenticated/catatan'
      path: '/catatan'
      fullPath: '/catatan'
      preLoaderRoute: typeof AuthenticatedCatatanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buku-alamat': {
      id: '/_authenticated/buku-alamat'
      path: '/buku-alamat'
      fullPath: '/buku-alamat'
      preLoaderRoute: typeof AuthenticatedBukuAlamatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balas-cepat': {
      id: '/_authenticated/balas-cepat'
      path: '/balas-cepat'
      fullPath: '/balas-cepat'
      preLoaderRoute: typeof AuthenticatedBalasCepatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/lovable/visual/produk-list': {
      id: '/lovable/visual/produk-list'
      path: '/lovable/visual/produk-list'
      fullPath: '/lovable/visual/produk-list'
      preLoaderRoute: typeof LovableVisualProdukListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/visual/komponen-review': {
      id: '/lovable/visual/komponen-review'
      path: '/lovable/visual/komponen-review'
      fullPath: '/lovable/visual/komponen-review'
      preLoaderRoute: typeof LovableVisualKomponenReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/visual/chat-deleted': {
      id: '/lovable/visual/chat-deleted'
      path: '/lovable/visual/chat-deleted'
      fullPath: '/lovable/visual/chat-deleted'
      preLoaderRoute: typeof LovableVisualChatDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prep-realtime-token': {
      id: '/api/public/prep-realtime-token'
      path: '/api/public/prep-realtime-token'
      fullPath: '/api/public/prep-realtime-token'
      preLoaderRoute: typeof ApiPublicPrepRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-ping': {
      id: '/api/public/ai-ping'
      path: '/api/public/ai-ping'
      fullPath: '/api/public/ai-ping'
      preLoaderRoute: typeof ApiPublicAiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/admin/worker-portal': {
      id: '/_authenticated/admin/worker-portal'
      path: '/admin/worker-portal'
      fullPath: '/admin/worker-portal'
      preLoaderRoute: typeof AuthenticatedAdminWorkerPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/security-scan-daily': {
      id: '/api/public/hooks/security-scan-daily'
      path: '/api/public/hooks/security-scan-daily'
      fullPath: '/api/public/hooks/security-scan-daily'
      preLoaderRoute: typeof ApiPublicHooksSecurityScanDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-queue-monitor': {
      id: '/api/public/hooks/email-queue-monitor'
      path: '/api/public/hooks/email-queue-monitor'
      fullPath: '/api/public/hooks/email-queue-monitor'
      preLoaderRoute: typeof ApiPublicHooksEmailQueueMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gudang/pesanan/$id': {
      id: '/_authenticated/gudang/pesanan/$id'
      path: '/pesanan/$id'
      fullPath: '/gudang/pesanan/$id'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdRouteImport
      parentRoute: typeof AuthenticatedGudangRoute
    }
    '/_authenticated/gudang/pesanan/$id/edit': {
      id: '/_authenticated/gudang/pesanan/$id/edit'
      path: '/edit'
      fullPath: '/gudang/pesanan/$id/edit'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdEditRouteImport
      parentRoute: typeof AuthenticatedGudangPesananIdRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedGudangPesananIdRouteChildren {
  AuthenticatedGudangPesananIdEditRoute: typeof AuthenticatedGudangPesananIdEditRoute
}

const AuthenticatedGudangPesananIdRouteChildren: AuthenticatedGudangPesananIdRouteChildren =
  {
    AuthenticatedGudangPesananIdEditRoute:
      AuthenticatedGudangPesananIdEditRoute,
  }

const AuthenticatedGudangPesananIdRouteWithChildren =
  AuthenticatedGudangPesananIdRoute._addFileChildren(
    AuthenticatedGudangPesananIdRouteChildren,
  )

interface AuthenticatedGudangRouteChildren {
  AuthenticatedGudangPesananIdRoute: typeof AuthenticatedGudangPesananIdRouteWithChildren
}

const AuthenticatedGudangRouteChildren: AuthenticatedGudangRouteChildren = {
  AuthenticatedGudangPesananIdRoute:
    AuthenticatedGudangPesananIdRouteWithChildren,
}

const AuthenticatedGudangRouteWithChildren =
  AuthenticatedGudangRoute._addFileChildren(AuthenticatedGudangRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBalasCepatRoute: typeof AuthenticatedBalasCepatRoute
  AuthenticatedBukuAlamatRoute: typeof AuthenticatedBukuAlamatRoute
  AuthenticatedCatatanRoute: typeof AuthenticatedCatatanRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedChatAuditRoute: typeof AuthenticatedChatAuditRoute
  AuthenticatedDeviceVerifyRoute: typeof AuthenticatedDeviceVerifyRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedEcerRoute: typeof AuthenticatedEcerRoute
  AuthenticatedEmailQueueRoute: typeof AuthenticatedEmailQueueRoute
  AuthenticatedGudangRoute: typeof AuthenticatedGudangRouteWithChildren
  AuthenticatedHutangPiutangRoute: typeof AuthenticatedHutangPiutangRoute
  AuthenticatedKontakRoute: typeof AuthenticatedKontakRoute
  AuthenticatedLabelPreviewRoute: typeof AuthenticatedLabelPreviewRoute
  AuthenticatedLinkPegawaiRoute: typeof AuthenticatedLinkPegawaiRoute
  AuthenticatedNotifikasiRoute: typeof AuthenticatedNotifikasiRoute
  AuthenticatedPengaturanAksesibilitasRoute: typeof AuthenticatedPengaturanAksesibilitasRoute
  AuthenticatedPengaturanApkRoute: typeof AuthenticatedPengaturanApkRoute
  AuthenticatedPengaturanAppModeRoute: typeof AuthenticatedPengaturanAppModeRoute
  AuthenticatedPengaturanBahasaRoute: typeof AuthenticatedPengaturanBahasaRoute
  AuthenticatedPengaturanIntegrasiSosialRoute: typeof AuthenticatedPengaturanIntegrasiSosialRoute
  AuthenticatedPengaturanKunciRoute: typeof AuthenticatedPengaturanKunciRoute
  AuthenticatedPengaturanPenyimpananRoute: typeof AuthenticatedPengaturanPenyimpananRoute
  AuthenticatedPengaturanScrollGuardRoute: typeof AuthenticatedPengaturanScrollGuardRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProfilChatRoute: typeof AuthenticatedProfilChatRoute
  AuthenticatedRequestRoute: typeof AuthenticatedRequestRoute
  AuthenticatedSesiRoute: typeof AuthenticatedSesiRoute
  AuthenticatedTugasRoute: typeof AuthenticatedTugasRoute
  AuthenticatedTugasBaruRoute: typeof AuthenticatedTugasBaruRoute
  AuthenticatedUndangRoute: typeof AuthenticatedUndangRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminWorkerPortalRoute: typeof AuthenticatedAdminWorkerPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBalasCepatRoute: AuthenticatedBalasCepatRoute,
  AuthenticatedBukuAlamatRoute: AuthenticatedBukuAlamatRoute,
  AuthenticatedCatatanRoute: AuthenticatedCatatanRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedChatAuditRoute: AuthenticatedChatAuditRoute,
  AuthenticatedDeviceVerifyRoute: AuthenticatedDeviceVerifyRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedEcerRoute: AuthenticatedEcerRoute,
  AuthenticatedEmailQueueRoute: AuthenticatedEmailQueueRoute,
  AuthenticatedGudangRoute: AuthenticatedGudangRouteWithChildren,
  AuthenticatedHutangPiutangRoute: AuthenticatedHutangPiutangRoute,
  AuthenticatedKontakRoute: AuthenticatedKontakRoute,
  AuthenticatedLabelPreviewRoute: AuthenticatedLabelPreviewRoute,
  AuthenticatedLinkPegawaiRoute: AuthenticatedLinkPegawaiRoute,
  AuthenticatedNotifikasiRoute: AuthenticatedNotifikasiRoute,
  AuthenticatedPengaturanAksesibilitasRoute:
    AuthenticatedPengaturanAksesibilitasRoute,
  AuthenticatedPengaturanApkRoute: AuthenticatedPengaturanApkRoute,
  AuthenticatedPengaturanAppModeRoute: AuthenticatedPengaturanAppModeRoute,
  AuthenticatedPengaturanBahasaRoute: AuthenticatedPengaturanBahasaRoute,
  AuthenticatedPengaturanIntegrasiSosialRoute:
    AuthenticatedPengaturanIntegrasiSosialRoute,
  AuthenticatedPengaturanKunciRoute: AuthenticatedPengaturanKunciRoute,
  AuthenticatedPengaturanPenyimpananRoute:
    AuthenticatedPengaturanPenyimpananRoute,
  AuthenticatedPengaturanScrollGuardRoute:
    AuthenticatedPengaturanScrollGuardRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProfilChatRoute: AuthenticatedProfilChatRoute,
  AuthenticatedRequestRoute: AuthenticatedRequestRoute,
  AuthenticatedSesiRoute: AuthenticatedSesiRoute,
  AuthenticatedTugasRoute: AuthenticatedTugasRoute,
  AuthenticatedTugasBaruRoute: AuthenticatedTugasBaruRoute,
  AuthenticatedUndangRoute: AuthenticatedUndangRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminWorkerPortalRoute: AuthenticatedAdminWorkerPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DownloadRouteChildren {
  DownloadVariantRoute: typeof DownloadVariantRoute
}

const DownloadRouteChildren: DownloadRouteChildren = {
  DownloadVariantRoute: DownloadVariantRoute,
}

const DownloadRouteWithChildren = DownloadRoute._addFileChildren(
  DownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRouteWithChildren,
  ErrorRoute: ErrorRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ICodeRoute: ICodeRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicAiPingRoute: ApiPublicAiPingRoute,
  ApiPublicPrepRealtimeTokenRoute: ApiPublicPrepRealtimeTokenRoute,
  LovableVisualChatDeletedRoute: LovableVisualChatDeletedRoute,
  LovableVisualKomponenReviewRoute: LovableVisualKomponenReviewRoute,
  LovableVisualProdukListRoute: LovableVisualProdukListRoute,
  ApiPublicHooksEmailQueueMonitorRoute: ApiPublicHooksEmailQueueMonitorRoute,
  ApiPublicHooksSecurityScanDailyRoute: ApiPublicHooksSecurityScanDailyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
