/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as AuthenticatedTugasRouteImport } from './routes/_authenticated.tugas'
import { Route as AuthenticatedRequestRouteImport } from './routes/_authenticated.request'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPengaturanKunciRouteImport } from './routes/_authenticated.pengaturan-kunci'
import { Route as AuthenticatedLinkPegawaiRouteImport } from './routes/_authenticated.link-pegawai'
import { Route as AuthenticatedLabelPreviewRouteImport } from './routes/_authenticated.label-preview'
import { Route as AuthenticatedKontakRouteImport } from './routes/_authenticated.kontak'
import { Route as AuthenticatedHutangPiutangRouteImport } from './routes/_authenticated.hutang-piutang'
import { Route as AuthenticatedGudangRouteImport } from './routes/_authenticated.gudang'
import { Route as AuthenticatedEcerRouteImport } from './routes/_authenticated.ecer'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated.diagnostics'
import { Route as AuthenticatedDeviceVerifyRouteImport } from './routes/_authenticated.device-verify'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated.chat.index'
import { Route as ApiPublicPrepRealtimeTokenRouteImport } from './routes/api/public/prep-realtime-token'
import { Route as ApiPublicAiPingRouteImport } from './routes/api/public/ai-ping'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated.chat.$conversationId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksSecurityScanDailyRouteImport } from './routes/api/public/hooks/security-scan-daily'
import { Route as ApiPublicHooksEmailQueueMonitorRouteImport } from './routes/api/public/hooks/email-queue-monitor'
import { Route as AuthenticatedGudangPesananIdRouteImport } from './routes/_authenticated.gudang.pesanan.$id'
import { Route as AuthenticatedGudangPesananIdEditRouteImport } from './routes/_authenticated.gudang.pesanan.$id.edit'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTugasRoute = AuthenticatedTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestRoute = AuthenticatedRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengaturanKunciRoute =
  AuthenticatedPengaturanKunciRouteImport.update({
    id: '/pengaturan-kunci',
    path: '/pengaturan-kunci',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLinkPegawaiRoute =
  AuthenticatedLinkPegawaiRouteImport.update({
    id: '/link-pegawai',
    path: '/link-pegawai',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabelPreviewRoute =
  AuthenticatedLabelPreviewRouteImport.update({
    id: '/label-preview',
    path: '/label-preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontakRoute = AuthenticatedKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHutangPiutangRoute =
  AuthenticatedHutangPiutangRouteImport.update({
    id: '/hutang-piutang',
    path: '/hutang-piutang',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGudangRoute = AuthenticatedGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEcerRoute = AuthenticatedEcerRouteImport.update({
  id: '/ecer',
  path: '/ecer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeviceVerifyRoute =
  AuthenticatedDeviceVerifyRouteImport.update({
    id: '/device-verify',
    path: '/device-verify',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiPublicPrepRealtimeTokenRoute =
  ApiPublicPrepRealtimeTokenRouteImport.update({
    id: '/api/public/prep-realtime-token',
    path: '/api/public/prep-realtime-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiPingRoute = ApiPublicAiPingRouteImport.update({
  id: '/api/public/ai-ping',
  path: '/api/public/ai-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSecurityScanDailyRoute =
  ApiPublicHooksSecurityScanDailyRouteImport.update({
    id: '/api/public/hooks/security-scan-daily',
    path: '/api/public/hooks/security-scan-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailQueueMonitorRoute =
  ApiPublicHooksEmailQueueMonitorRouteImport.update({
    id: '/api/public/hooks/email-queue-monitor',
    path: '/api/public/hooks/email-queue-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGudangPesananIdRoute =
  AuthenticatedGudangPesananIdRouteImport.update({
    id: '/pesanan/$id',
    path: '/pesanan/$id',
    getParentRoute: () => AuthenticatedGudangRoute,
  } as any)
const AuthenticatedGudangPesananIdEditRoute =
  AuthenticatedGudangPesananIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedGudangPesananIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/error': typeof ErrorRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ecer': typeof AuthenticatedEcerRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/kontak': typeof AuthenticatedKontakRoute
  '/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/request': typeof AuthenticatedRequestRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/t/$token': typeof TTokenRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/error': typeof ErrorRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ecer': typeof AuthenticatedEcerRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/kontak': typeof AuthenticatedKontakRoute
  '/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/request': typeof AuthenticatedRequestRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/t/$token': typeof TTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/error': typeof ErrorRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/ecer': typeof AuthenticatedEcerRoute
  '/_authenticated/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/_authenticated/hutang-piutang': typeof AuthenticatedHutangPiutangRoute
  '/_authenticated/kontak': typeof AuthenticatedKontakRoute
  '/_authenticated/label-preview': typeof AuthenticatedLabelPreviewRoute
  '/_authenticated/link-pegawai': typeof AuthenticatedLinkPegawaiRoute
  '/_authenticated/pengaturan-kunci': typeof AuthenticatedPengaturanKunciRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/request': typeof AuthenticatedRequestRoute
  '/_authenticated/tugas': typeof AuthenticatedTugasRoute
  '/t/$token': typeof TTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/public/ai-ping': typeof ApiPublicAiPingRoute
  '/api/public/prep-realtime-token': typeof ApiPublicPrepRealtimeTokenRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/api/public/hooks/email-queue-monitor': typeof ApiPublicHooksEmailQueueMonitorRoute
  '/api/public/hooks/security-scan-daily': typeof ApiPublicHooksSecurityScanDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/error'
    | '/pricing'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/audit'
    | '/chat'
    | '/device-verify'
    | '/diagnostics'
    | '/ecer'
    | '/gudang'
    | '/hutang-piutang'
    | '/kontak'
    | '/label-preview'
    | '/link-pegawai'
    | '/pengaturan-kunci'
    | '/profil'
    | '/request'
    | '/tugas'
    | '/t/$token'
    | '/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/chat/'
    | '/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/gudang/pesanan/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/download'
    | '/error'
    | '/pricing'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/audit'
    | '/device-verify'
    | '/diagnostics'
    | '/ecer'
    | '/gudang'
    | '/hutang-piutang'
    | '/kontak'
    | '/label-preview'
    | '/link-pegawai'
    | '/pengaturan-kunci'
    | '/profil'
    | '/request'
    | '/tugas'
    | '/t/$token'
    | '/'
    | '/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/chat'
    | '/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/gudang/pesanan/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/error'
    | '/pricing'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/device-verify'
    | '/_authenticated/diagnostics'
    | '/_authenticated/ecer'
    | '/_authenticated/gudang'
    | '/_authenticated/hutang-piutang'
    | '/_authenticated/kontak'
    | '/_authenticated/label-preview'
    | '/_authenticated/link-pegawai'
    | '/_authenticated/pengaturan-kunci'
    | '/_authenticated/profil'
    | '/_authenticated/request'
    | '/_authenticated/tugas'
    | '/t/$token'
    | '/_authenticated/'
    | '/_authenticated/chat/$conversationId'
    | '/api/public/ai-ping'
    | '/api/public/prep-realtime-token'
    | '/_authenticated/chat/'
    | '/_authenticated/gudang/pesanan/$id'
    | '/api/public/hooks/email-queue-monitor'
    | '/api/public/hooks/security-scan-daily'
    | '/lovable/email/queue/process'
    | '/_authenticated/gudang/pesanan/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  ErrorRoute: typeof ErrorRoute
  PricingRoute: typeof PricingRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicAiPingRoute: typeof ApiPublicAiPingRoute
  ApiPublicPrepRealtimeTokenRoute: typeof ApiPublicPrepRealtimeTokenRoute
  ApiPublicHooksEmailQueueMonitorRoute: typeof ApiPublicHooksEmailQueueMonitorRoute
  ApiPublicHooksSecurityScanDailyRoute: typeof ApiPublicHooksSecurityScanDailyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tugas': {
      id: '/_authenticated/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof AuthenticatedTugasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/request': {
      id: '/_authenticated/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AuthenticatedRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan-kunci': {
      id: '/_authenticated/pengaturan-kunci'
      path: '/pengaturan-kunci'
      fullPath: '/pengaturan-kunci'
      preLoaderRoute: typeof AuthenticatedPengaturanKunciRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/link-pegawai': {
      id: '/_authenticated/link-pegawai'
      path: '/link-pegawai'
      fullPath: '/link-pegawai'
      preLoaderRoute: typeof AuthenticatedLinkPegawaiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/label-preview': {
      id: '/_authenticated/label-preview'
      path: '/label-preview'
      fullPath: '/label-preview'
      preLoaderRoute: typeof AuthenticatedLabelPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kontak': {
      id: '/_authenticated/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof AuthenticatedKontakRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hutang-piutang': {
      id: '/_authenticated/hutang-piutang'
      path: '/hutang-piutang'
      fullPath: '/hutang-piutang'
      preLoaderRoute: typeof AuthenticatedHutangPiutangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gudang': {
      id: '/_authenticated/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof AuthenticatedGudangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ecer': {
      id: '/_authenticated/ecer'
      path: '/ecer'
      fullPath: '/ecer'
      preLoaderRoute: typeof AuthenticatedEcerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/device-verify': {
      id: '/_authenticated/device-verify'
      path: '/device-verify'
      fullPath: '/device-verify'
      preLoaderRoute: typeof AuthenticatedDeviceVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/prep-realtime-token': {
      id: '/api/public/prep-realtime-token'
      path: '/api/public/prep-realtime-token'
      fullPath: '/api/public/prep-realtime-token'
      preLoaderRoute: typeof ApiPublicPrepRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-ping': {
      id: '/api/public/ai-ping'
      path: '/api/public/ai-ping'
      fullPath: '/api/public/ai-ping'
      preLoaderRoute: typeof ApiPublicAiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/security-scan-daily': {
      id: '/api/public/hooks/security-scan-daily'
      path: '/api/public/hooks/security-scan-daily'
      fullPath: '/api/public/hooks/security-scan-daily'
      preLoaderRoute: typeof ApiPublicHooksSecurityScanDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-queue-monitor': {
      id: '/api/public/hooks/email-queue-monitor'
      path: '/api/public/hooks/email-queue-monitor'
      fullPath: '/api/public/hooks/email-queue-monitor'
      preLoaderRoute: typeof ApiPublicHooksEmailQueueMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gudang/pesanan/$id': {
      id: '/_authenticated/gudang/pesanan/$id'
      path: '/pesanan/$id'
      fullPath: '/gudang/pesanan/$id'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdRouteImport
      parentRoute: typeof AuthenticatedGudangRoute
    }
    '/_authenticated/gudang/pesanan/$id/edit': {
      id: '/_authenticated/gudang/pesanan/$id/edit'
      path: '/edit'
      fullPath: '/gudang/pesanan/$id/edit'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdEditRouteImport
      parentRoute: typeof AuthenticatedGudangPesananIdRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedGudangPesananIdRouteChildren {
  AuthenticatedGudangPesananIdEditRoute: typeof AuthenticatedGudangPesananIdEditRoute
}

const AuthenticatedGudangPesananIdRouteChildren: AuthenticatedGudangPesananIdRouteChildren =
  {
    AuthenticatedGudangPesananIdEditRoute:
      AuthenticatedGudangPesananIdEditRoute,
  }

const AuthenticatedGudangPesananIdRouteWithChildren =
  AuthenticatedGudangPesananIdRoute._addFileChildren(
    AuthenticatedGudangPesananIdRouteChildren,
  )

interface AuthenticatedGudangRouteChildren {
  AuthenticatedGudangPesananIdRoute: typeof AuthenticatedGudangPesananIdRouteWithChildren
}

const AuthenticatedGudangRouteChildren: AuthenticatedGudangRouteChildren = {
  AuthenticatedGudangPesananIdRoute:
    AuthenticatedGudangPesananIdRouteWithChildren,
}

const AuthenticatedGudangRouteWithChildren =
  AuthenticatedGudangRoute._addFileChildren(AuthenticatedGudangRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDeviceVerifyRoute: typeof AuthenticatedDeviceVerifyRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedEcerRoute: typeof AuthenticatedEcerRoute
  AuthenticatedGudangRoute: typeof AuthenticatedGudangRouteWithChildren
  AuthenticatedHutangPiutangRoute: typeof AuthenticatedHutangPiutangRoute
  AuthenticatedKontakRoute: typeof AuthenticatedKontakRoute
  AuthenticatedLabelPreviewRoute: typeof AuthenticatedLabelPreviewRoute
  AuthenticatedLinkPegawaiRoute: typeof AuthenticatedLinkPegawaiRoute
  AuthenticatedPengaturanKunciRoute: typeof AuthenticatedPengaturanKunciRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRequestRoute: typeof AuthenticatedRequestRoute
  AuthenticatedTugasRoute: typeof AuthenticatedTugasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDeviceVerifyRoute: AuthenticatedDeviceVerifyRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedEcerRoute: AuthenticatedEcerRoute,
  AuthenticatedGudangRoute: AuthenticatedGudangRouteWithChildren,
  AuthenticatedHutangPiutangRoute: AuthenticatedHutangPiutangRoute,
  AuthenticatedKontakRoute: AuthenticatedKontakRoute,
  AuthenticatedLabelPreviewRoute: AuthenticatedLabelPreviewRoute,
  AuthenticatedLinkPegawaiRoute: AuthenticatedLinkPegawaiRoute,
  AuthenticatedPengaturanKunciRoute: AuthenticatedPengaturanKunciRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRequestRoute: AuthenticatedRequestRoute,
  AuthenticatedTugasRoute: AuthenticatedTugasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  ErrorRoute: ErrorRoute,
  PricingRoute: PricingRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicAiPingRoute: ApiPublicAiPingRoute,
  ApiPublicPrepRealtimeTokenRoute: ApiPublicPrepRealtimeTokenRoute,
  ApiPublicHooksEmailQueueMonitorRoute: ApiPublicHooksEmailQueueMonitorRoute,
  ApiPublicHooksSecurityScanDailyRoute: ApiPublicHooksSecurityScanDailyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
