/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedGudangRouteImport } from './routes/_authenticated.gudang'
import { Route as AuthenticatedDeviceVerifyRouteImport } from './routes/_authenticated.device-verify'
import { Route as AuthenticatedGudangPesananIdRouteImport } from './routes/_authenticated.gudang.pesanan.$id'
import { Route as AuthenticatedGudangPesananIdEditRouteImport } from './routes/_authenticated.gudang.pesanan.$id.edit'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGudangRoute = AuthenticatedGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeviceVerifyRoute =
  AuthenticatedDeviceVerifyRouteImport.update({
    id: '/device-verify',
    path: '/device-verify',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGudangPesananIdRoute =
  AuthenticatedGudangPesananIdRouteImport.update({
    id: '/pesanan/$id',
    path: '/pesanan/$id',
    getParentRoute: () => AuthenticatedGudangRoute,
  } as any)
const AuthenticatedGudangPesananIdEditRoute =
  AuthenticatedGudangPesananIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedGudangPesananIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/error': typeof ErrorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/error': typeof ErrorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/error': typeof ErrorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/_authenticated/device-verify': typeof AuthenticatedDeviceVerifyRoute
  '/_authenticated/gudang': typeof AuthenticatedGudangRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/gudang/pesanan/$id': typeof AuthenticatedGudangPesananIdRouteWithChildren
  '/_authenticated/gudang/pesanan/$id/edit': typeof AuthenticatedGudangPesananIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/error'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trust'
    | '/device-verify'
    | '/gudang'
    | '/gudang/pesanan/$id'
    | '/gudang/pesanan/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/error'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trust'
    | '/device-verify'
    | '/gudang'
    | '/'
    | '/gudang/pesanan/$id'
    | '/gudang/pesanan/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/error'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trust'
    | '/_authenticated/device-verify'
    | '/_authenticated/gudang'
    | '/_authenticated/'
    | '/_authenticated/gudang/pesanan/$id'
    | '/_authenticated/gudang/pesanan/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ErrorRoute: typeof ErrorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gudang': {
      id: '/_authenticated/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof AuthenticatedGudangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/device-verify': {
      id: '/_authenticated/device-verify'
      path: '/device-verify'
      fullPath: '/device-verify'
      preLoaderRoute: typeof AuthenticatedDeviceVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gudang/pesanan/$id': {
      id: '/_authenticated/gudang/pesanan/$id'
      path: '/pesanan/$id'
      fullPath: '/gudang/pesanan/$id'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdRouteImport
      parentRoute: typeof AuthenticatedGudangRoute
    }
    '/_authenticated/gudang/pesanan/$id/edit': {
      id: '/_authenticated/gudang/pesanan/$id/edit'
      path: '/edit'
      fullPath: '/gudang/pesanan/$id/edit'
      preLoaderRoute: typeof AuthenticatedGudangPesananIdEditRouteImport
      parentRoute: typeof AuthenticatedGudangPesananIdRoute
    }
  }
}

interface AuthenticatedGudangPesananIdRouteChildren {
  AuthenticatedGudangPesananIdEditRoute: typeof AuthenticatedGudangPesananIdEditRoute
}

const AuthenticatedGudangPesananIdRouteChildren: AuthenticatedGudangPesananIdRouteChildren =
  {
    AuthenticatedGudangPesananIdEditRoute:
      AuthenticatedGudangPesananIdEditRoute,
  }

const AuthenticatedGudangPesananIdRouteWithChildren =
  AuthenticatedGudangPesananIdRoute._addFileChildren(
    AuthenticatedGudangPesananIdRouteChildren,
  )

interface AuthenticatedGudangRouteChildren {
  AuthenticatedGudangPesananIdRoute: typeof AuthenticatedGudangPesananIdRouteWithChildren
}

const AuthenticatedGudangRouteChildren: AuthenticatedGudangRouteChildren = {
  AuthenticatedGudangPesananIdRoute:
    AuthenticatedGudangPesananIdRouteWithChildren,
}

const AuthenticatedGudangRouteWithChildren =
  AuthenticatedGudangRoute._addFileChildren(AuthenticatedGudangRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDeviceVerifyRoute: typeof AuthenticatedDeviceVerifyRoute
  AuthenticatedGudangRoute: typeof AuthenticatedGudangRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDeviceVerifyRoute: AuthenticatedDeviceVerifyRoute,
  AuthenticatedGudangRoute: AuthenticatedGudangRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ErrorRoute: ErrorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
